# Generated by Django 2.2.13 on 2021-02-06 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('shirt', 'Shirt'), ('sport', 'Sport Wear'), ('outer', 'Outerwear')], default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='label',
            field=models.CharField(choices=[('pri', 'primary'), ('sec', 'secondary'), ('dan', 'danger')], default=0, max_length=10),
            preserve_default=False,
        ),
    ]
